@startuml

abstract class Persona{
    - String dni <<final>>
    - String nombreComp
    - LocalDateTime fechaNaci 
    - String sexo
    ---
    + void mostrarDatos()

}

class PersonalAdmin <<final>>{

    + void registrarPaciente()
    + void modificarDatosPaciente()
    + void darAltaPaciente()

}

class Paciente <<final>>{

    - int numeroPaciente 
    - String direccion 
    - int numeroTelefono
    - String correoElectronico
    - int telefonoEmergencia
    - HistorialMedico historial
    
    + void MostrarDatos()

}

class HistorialMedico{

    - String enfermedadesPrevias
    - String alergias 
    - String intervencionesQuirurgicas
    - String EnfermedadesCronicas
    - String Medicacion 
    
    + void mostrarHistorial()
}

class Medico <<final>> {
    + void consultarHistorial()
    + void modificarHistorial()
    + void añadirDiagnostico()
    + void añadirTratamiento()
}

class AreaFacturacion{
    + void generarFactura()

}


Persona <|-- Paciente
Persona <|-- Medico
Persona <|-- PersonalAdmin
Paciente "1" --> "1" HistorialMedico : POSEE
PersonalAdmin "1" --> "*" Paciente : REGISTRA
Medico "*" --> "*" HistorialMedico : MODIFICA
Medico "1" --> "*" AreaFacturacion : NOTIFICA
Medico "1" --> "*" Paciente : ATIENDE
@enduml
