@startuml
title Diagrama de Actividad - Gestión Clínica (Atención al Paciente)

|Personal Administrativo|
start

:Paciente llega al hospital;
:Verificar llegada del paciente;
:Solicitar DNI al paciente;

if (¿DNI registrado en el sistema?) then (No  \n Paciente nuevo)

    :Solicitar datos personales completos;

    :Recopilar antecedentes médicos;

    :Asignar número de Historia Clínica único;


else (Sí \n Paciente recurrente)

    :Cargar historial automáticamente por DNI;


    if (¿Hay cambios en los datos?) then (Sí)
        :Actualizar datos personales;
        :Añadir nuevos antecedentes médicos;

    else (No \n Datos coinciden)

    endif

endif

' El médico lleva el control clínico y de modificaciones dentro del historial clinico del paciente 
' El admin gestiona los cambios administrativos del paciente 

|Médico|

:Acceder a la historia clínica digital;
:Añadir diagnósticos al historial;
:Añadir tratamientos al historial;

|Personal Administrativo|

if (¿Se solicita cambio de médico o unidad?) then (Sí)

    :Reasignar médico responsable;
    :Actualizar historial con nuevo médico/unidad;
else (No)

endif

if (¿Continuación del paciente desde consulta?) then (Baja administrativa)

    if (¿Tipo de baja?) then (Permanente)

        :Eliminar registro del paciente;

        stop

    else (Temporal)

        :Suspender registro temporalmente;

        stop

    endif

else (Diagnóstico y tratamiento asignados)


' El médico aplica y hace seguimiento al paciente para ver si el tratamiento realiza el efecto 
' esperado por el medico


    |Médico|

    :Iniciar tratamiento prescrito;
    :Seguimiento médico activo;

    ' El sistema notifica automáticamente a facturación
    ' si el procedimiento requiere pago.
    ' Facturación lo consulta desde su propio menú

    :Notificar a facturación si requiere pago;

    |Personal de Facturación|

    ' El personal de Facturación es quien revisa si se ha enviado una notificacion de cobro al paciente 
    ' esa notificación es enviada de parte del médico en caso de se crea cònveniente dependiendo de si 
    ' despues de la consulta y tratamiento resulta necesario

    :Ver notificaciones de procedimientos de pago;
    :Generar factura al paciente si procede;

    |Personal Administrativo|

    if (¿Se solicita cambio de médico o unidad?) then (Sí)
        :Reasignar médico responsable;
        :Actualizar historial con nuevo médico/unidad;
    else (No)

    endif

    if (¿Finalización del tratamiento?) then (Abandono o baja)

        if (¿Tipo de baja?) then (Permanente)

            :Eliminar registro del paciente;

            stop
        else (Temporal)

            :Suspender registro temporalmente;

            stop
        endif

    else (Tratamiento completado)

        |Médico|
        :Conceder alta médica al paciente;

        ' El medico es el único después de una evaluación al paciente si se le puede realizar el alta medica 

        |Personal Administrativo|
        :Actualizar historial clínico;
        :Cerrar registro de atención;
        
        stop

    endif

endif

@enduml